---
layout: post
title: why promise
categories: pages
excerpt: promise
tags: javascript
---
#### 背景  
今天小铁去面试被问到promise的诞生是为了解决哪些问题？小铁不暇思索的说道：promise的诞生是为了用同步的方式写异步，提高代码的可读性。然后，面试官对这回答不是很满意，说这只是一方面，没有答到点上bulabula...回来后小铁总结发现，自己确实对promise这个知识点的理解只是停留在表面，所以有了这篇知识点总结。    

#### Promise 解决了哪些问题
```javascript
step1(function (value1) {
  step2(value1, function(value2) {
    step3(value2, function(value3) {
      step4(value3, function(value4) {
        // Do something with value4
      });
    });
  });
});

new Promise((resolve) => {
  step1(resolve(value1))
}).then(res => {
  return new Promise((resolve) => {
    step2(resolve)
  })
}).then(res => {
  return new Promise((resolve) => {
    step3(resolve)
  })
}).then(res => {
  return new Promise((resolve) => {
    step4(resolve)
  })
}).then(res => {
  // Do something with value4
}).catch(err => {
  // 统一处理异常
})
```
1. Promise提高了代码的可读性、可维护性
2. 解决了回调嵌套的异常捕获问题（不能throw new Error()并在外部捕获异常）
3. 内层函数携带外层函数作用域，容易导致内存泄漏

#### catch 和 onRejected
```javascript
// 1
new Promise(function(resolve, reject) {
  1 ? resolve() : reject()
}).then(function() {
  console.log('resolve');
}, function(err) {
  console.log('reject');
})
// 2
new Promise(function(resolve, reject) {
  1 ? resolve() : reject()
}).then(function() {
  console.log('resolve');
}).catch(function(err) {
  console.log('reject');
})
// 3
new Promise(function(resolve, reject) {
  1 ? resolve() : reject()
}).then(function() {
  console.log('resolve');
}).then(null, function(err) {
  console.log('reject');
})

```
2 和 3 完全一样。1 和 2 有细微的区别，当第一个 onFulfilled 内抛出异常时 1 的 onRejected并不会被执行（二者不能同时执行），而 2 的catch回调会被执行。

Promise.prototype.then(onFulfilled, onRejected) 方法返回一个由onFulfilled/onRejected确定的Promise。当 onFulfilled / onRejected 抛出一个错误，或者返回一个拒绝的 Promise ，then 返回一个 rejected Promise；当 onFulfilled / onRejected 返回一个 resolves Promise，或者返回任何其他值(或者没有动态的设置返回值)，then 返回一个 resolved Promise。

#### Promise.all(iterable)
这个方法返回一个新的promise对象，该promise对象在iterable里所有的promise对象都成功的时候才会触发成功，一旦有任何一个iterable里面的promise对象失败则立即触发该promise对象的失败。这个新的promise对象在触发成功状态以后，会把一个包含iterable里所有promise返回值的数组作为成功回调的返回值，顺序跟iterable的顺序保持一致；如果这个新的promise对象触发了失败状态，它会把iterable里第一个触发失败的promise对象的错误信息作为它的失败错误信息。Promise.all方法常被用于处理多个promise对象的状态集合。

#### Promise.race(iterable)
当iterable参数里的任意一个子promise被成功或失败后，父promise马上也会用子promise的成功返回值或失败详情作为参数调用父promise绑定的相应句柄，并返回该promise对象。
