---
layout: post
title: Why Promise
categories: pages
excerpt: Promise
tags: javascript
---

故事是这样的：小铁去某厂面试被问到：“`Promise`的出现是为了解决哪些问题？”，他胸有成竹脱口而出：“`Promise`的出现是为提高代码的可读性，用同步的方式来写异步”。然鹅，面试官对这个回答并不满意，说：“这只是一方面，并没有答到点上。`Promise`的出现是为了......”。事后小铁发现自己对`Promise`的理解还只是停留在表面，所以有了下面这篇`Promise`知识点的总结。   

小铁觉得要深刻的理解一个概念，大体可以从以下三个问题出发。

1. 是什么 ？
2. 为什么 ？
3. 怎么做 ？

那么，下面我们就带着这三个问题撸一撸`Promise`吧 ~

慢着！`Promise`是个抽象的概念，直接去理解一个抽象的概念似乎并不容易。我们先搞懂为什么，再去探索它是什么会不会更容易一些呢？


### 为什么需要 Promise

```javascript
function getUser(name) {
  var sql = 'SELECT * FROM users WHERE name=?'
  var user = query(sql, name) // <- blocking
  if (!user) throw new Error('no user!')
  return user
}
```

上面这段代码存在一个问题，查库方法`query()`会阻塞后续代码的执行，直至数据库返回查询结果。  

接着，我们来看看下面这段代码

```javascript
function getUser(name, callback) {
  var sql = 'SELECT * FROM users WHERE name=?'
  query(sql, name, function (error, user) {
    if (error) {
      callback(error) // 为什么不是 throw ？
    } else if (!user) {
      callback(new Error('no user!'))
    } else {
      callback(null, user)
    }
    // 为什么没有 return ?
  })
}
```

`query()`允许将一个函数作为第三参数传入，而且这里的`query()`不会阻塞后续代码的执行。
这个作为参数的函数就是回调函数，它会在数据库返回查询结果的时候被执行，是异步的。  

**所以，通过回调函数的方式我们解决了阻塞的问题。**  

但是，回调函数存在以下四个局限。  

**一、 在回调函数里我们不能使用关键字 throw 和 return了。**

> 回调函数是异步的，所以回调函数内部通过`throw`抛出的异常无法被外部的`try catch`捕获


**二、 回调函数的执行次数得不到保证。怎么理解呢？举个🌰**

> ```javascript
  function getUsers(names, callback) {
    var sql = 'SELECT * FROM users WHERE name=?'
    var users = []
    names.forEach(name => {
      query(sql, name, function (error, user) {
        if (error) {
          callback(error)
        } else if (!user) {
          callback(new Error('no user!'))
        } else {
          users.push(user)
          if (users.length === names.length) {
            callback(null, users)
          }
        }
      })
    })
  }
  ```
  当names为两个无效的用户名集合，`query()`抛出异常时，callback依然会被执行两次！！


**三、 回调函数中不能利用函数的调用栈了。由回调函数的异步性质导致。**

> 如果你不知道函数调用栈的作用，可以看下这篇文章[你不知道的 JS 错误和调用栈常识](https://zhuanlan.zhihu.com/p/25644447)


**四、 回调函数的易用性不高。怎么理解呢？再举个🌰：**

> ```javascript
  getUser('mjackson', function (user) {
    getNewTweets(user, function (tweets) {
      updateTimeline(tweets)
    })
  })
  ```
  当多个异步逻辑存在先后依赖的时候，我们的代码就像喝水都长膘的胖子，稍不留神就会横向生长。这样的代码（回调地狱）既不利于阅读也不利于维护。

> 推荐阅读这篇关于回调地狱的文章 [Managing Node.js Callback Hell](https://medium.com/@wavded/managing-node-js-callback-hell-1fe03ba8baf)

<br>

总结一下上面说的几个问题

1. **回调函数内部无法使用回调栈（无法使用关键字throw和return）**  

2. **当错误发生时，回调函数的执行次数得不到保证**  

3. **回调函数嵌过多难以维护，可读性差**

而`Promise`的出现就是为了解决了上述3个问题，我们接下来看看`Promise`到底是个什么东西？


### 什么是 Promise
> A Promise is an object that is used as a placeholder for the eventual results of a deferred (and possibly asynchronous) computation.

以上是标准（ECMA）对Promise的定义。   

通俗点说就是：Promise 对象是一个代理对象（代理一个值），被代理的值在Promise对象创建时可能是未知的。
它允许你为异步代码执行结果的成功和失败分别绑定相应的处理方法（resolve/reject）。    

这让异步方法可以像同步方法那样返回值，但是并非立即返回执行的结果，因为毕竟执行的是异步代码，因此，它会返回一个Promise对象，如前所说，它是一个代理的对象，代理了最终返回的值，可以在后期使用。

Promise有以下几种状态:

* pending: 初始状态。
* fulfilled: 意味着操作成功。
* rejected: 意味着操作失败。

![promise流程示意图](/images/promises.png)


创建一个Promise对象，在executor函数体内执行异步操作 ~

```javascript
new Promise(
    /* executor */
    function(resolve, reject){...}
);
```


**Promise.prototype.then()**

then() 方法返回一个 Promise，绑定处理异步代码执行的结果的函数。它最多需要有两个参数：Promise的成功和失败情况的回调函数。   

语法
```javascript
p.then(onFulfilled, onRejected);
```

`Promise.prototype.then(onFulfilled, onRejected)`方法返回一个由`onFulfilled/onRejected`方法确定的`Promise`。  

当`onFulfilled/onRejected`方法抛出一个错误，或者返回一个拒绝的`Promise` ，`then`返回一个`rejected Promise`。   

当`onFulfilled/onRejected`方法返回一个`fulfilled Promise`，或者返回任何其他值(或者没有动态的设置返回值)，`then`返回一个`fulfilled Promise`。


**Promise.prototype.catch()**

catch() 方法返回一个Promise，只处理拒绝的情况。它的行为与调用Promise.prototype.then(undefined, onRejected) 相同。   

语法
```javascript
p.catch(onRejected);
```


**catch 和 onRejected 的区别**

```javascript
// A
new Promise(function(resolve, reject) {
  1 ? resolve() : reject()
}).then(function() {
  console.log('resolve');
}, function(err) {
  console.log('reject');
})
// B
new Promise(function(resolve, reject) {
  1 ? resolve() : reject()
}).then(function() {
  console.log('resolve');
}).catch(function(err) {
  console.log('reject');
})
// C
new Promise(function(resolve, reject) {
  1 ? resolve() : reject()
}).then(function() {
  console.log('resolve');
}).then(null, function(err) {
  console.log('reject');
})
```
B和C完全一样。A和B有细微的区别，当第一个`onFulfilled`内抛出异常时A的`onRejected`并不会被执行（二者不能同时执行），而B的`catch`回调会被执行。


**Promise.all(iterable)**   

这个方法返回一个新的Promise对象，该`Promise`对象在`iterable`里所有的Promise对象都成功的时候才会触发成功，一旦有任何一个`iterable`里面的Promise对象失败则立即触发该`Promise`对象的失败。   

这个新的`Promise`对象在触发成功状态以后，会把一个包含`iterable`里所有`Promise`返回值的数组作为成功回调的返回值，顺序跟`iterable`的顺序保持一致；如果这个新的`Promise`对象触发了失败状态，它会把`iterable`里第一个触发失败的`Promise`对象的错误信息作为它的失败错误信息。   

`Promise.all`方法常被用于处理多个`Promise`对象的状态集合。


**Promise.race(iterable)**    

当`iterable`参数里的任意一个子`Promise`成功或失败后，父`Promise`马上也会用子`Promise`的成功返回值或失败详情作为参数调用父`Promise`绑定的相应句柄，并返回该`Promise`对象。


### 那...怎么使用 Promise 呢

现在我们来看看用`Promise`怎么解决上述三个问题。
Talk is cheap, show you the code !  

第一个问题，回调函数内部无法使用回调栈（无法使用关键字throw和return）

```javascript
function getUser(name) {
  var sql = 'SELECT * FROM users WHERE name=?'
  var user = query(sql, name) // <- blocking
  if (!user) throw new Error('no user!')
  return user
}

try {
  getUser('mjackson')
} catch(e) {
  console.error(e)
}

// using callbacks
function getUser(name, callback) {
  var sql = 'SELECT * FROM users WHERE name=?'
  query(sql, name, function (error, user) {
    if (error) {
      callback(error)
    } else if (!user) {
      callback(new Error('no user!'))
    } else {
      callback(null, user)
    }
  })
}

getUser('mjackson', (error, user) => {
  if (error) return console.error(error)
  console.log(user)
})

// using promises
function getUser(name) {
  var sql = 'SELECT * FROM users WHERE name=?'
  var executor = function (resolve, reject) {
    query(sql, name, (error, user) => {
      error ? reject(error) : resolve(user)
    })
  }
  return new Promise(executor)
}

getUser('mjackson')
  .then(user => {
    if (!user) throw new Error('no user!')
    return Promise.resolve(user)
  })
  .then(console.log, console.error)
```

第二个问题，当错误发生时，回调函数的执行次数得不到保证

```javascript
// using callbacks
function getUsers(names, callback) {
  var sql = 'SELECT * FROM users WHERE name=?'
  var users = []
  names.forEach(name => {
    query(sql, name, function (error, user) {
      if (error) {
        callback(error)
      } else if (!user) {
        callback(new Error('no user!'))
      } else {
        users.push(user)
        if (users.length === names.length) {
          callback(null, users)
        }
      }
    })
  })
}

getUsers([NaN, true], (error, users) => {
  if (error) return console.error(error)
  console.log(users)
})

// using promises
function getUsers(names) {
  var sql = 'SELECT * FROM users WHERE name=?'
  var queryPromises = names.map(name => {
    var executor = function (resolve, reject) {
      query(sql, name, (error, user) => {
        error ? reject(error) : resolve(user)
      })
    }
    return new Promise(executor)
  })
  return Promise.all(queryPromises)
}

getUsers([NaN, true])
  .then(console.log, console.error)

```

第三个问题，回调函数嵌过多难以维护，可读性差

```javascript
var user = getUser('mjackson')
var tweets = getNewTweets(user)
updateTimeline(tweets)

// using callbacks
getUser('mjackson', function (user) {
  getNewTweets(user, function (tweets) {
    updateTimeline(tweets)
  })
})

// using promises
getUser('mjackson')
  .then(getNewTweets)
  .then(updateTimeline)
```


以上是小铁这次的总结 ~  

<br>

最后，思考一下面 4 个 promise 之间有什么区别 ？

```javascript
  // doSomething,doSomethingElse均返回一个Promise对象
  doSomething().then(function () {
    return doSomethingElse()
  })

  doSomething().then(function () {
    doSomethingElse()
  })

  doSomething().then(doSomethingElse())

  doSomething().then(doSomethingElse)
```

> 答案见 [We have a problem with promises](https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html)

<br><br>

参考文档：[MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)、[ECMA](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-promise-objects)、[你不知道的 JS 错误和调用栈常识](https://zhuanlan.zhihu.com/p/25644447)、[JavaScript Errors and Stack Traces in Depth](http://lucasfcosta.com/2017/02/17/JavaScript-Errors-and-Stack-Traces.html)
、[Redemption from Callback Hell](https://www.youtube.com/watch?v=hf1T_AONQJU&feature=youtu.be)
